# Generated by Django 5.1.7 on 2025-06-30 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('department', '0002_initial'),
        ('fiscal_year', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('leave_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('roaster', 'Roster')], default='paid', max_length=50, verbose_name='Type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('A', 'All')], default='A', max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('A', 'All')], default='A', max_length=1)),
                ('number_of_days', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('show_on_employee', models.BooleanField(default=True, verbose_name='Display on Team Member?')),
                ('prorata_status', models.BooleanField(default=False, verbose_name='Enable Prorata?')),
                ('encashable_status', models.BooleanField(default=False, verbose_name='Enable Encashable?')),
                ('half_leave_status', models.BooleanField(default=False, verbose_name='Enable Half Leave?')),
                ('half_leave_type', models.CharField(choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], default='first_half', max_length=50)),
                ('carry_forward_status', models.BooleanField(default=False, verbose_name='Enable Carry Forward?')),
                ('sandwich_rule_status', models.BooleanField(default=False, verbose_name='Enable Sandwich Rule?')),
                ('pre_inform_days', models.IntegerField(blank=True, null=True, verbose_name='Leave request should be submitted before (in days)')),
                ('max_per_day_leave', models.IntegerField(blank=True, null=True, verbose_name='Maximum number of days per request')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')),
                ('job_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation'), ('all', 'All')], default='all', max_length=50, verbose_name='Job Type')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='leave_type_branches', to='branch.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='leave_type_departments', to='department.department')),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_fiscal_year', to='fiscal_year.fiscalyear')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Verified', 'Verified'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Applied')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_updated_by', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_leave', to='leave.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leave', models.FloatField()),
                ('leave_taken', models.FloatField()),
                ('leave_remaining', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_employee', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave_updated_by', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_leave_type', to='leave.leavetype')),
            ],
        ),
    ]
