# Generated by Django 5.1.7 on 2025-06-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_type', models.CharField(choices=[('ad', 'AD'), ('bs', 'BS')], default='ad', max_length=2, verbose_name='Calendar Type')),
                ('shift_threshold', models.IntegerField(help_text='Threshold in minutes for shift calculations', verbose_name='Shift Threshold (minutes)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
                'ordering': ['-created_on'],
            },
        ),
    ]
