# Generated by Django 5.1.7 on 2025-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='calendar_type',
            field=models.CharField(choices=[('bs', 'BS'), ('ad', 'AD')], default='bs', max_length=2, verbose_name='Calendar Type'),
        ),
    ]
