# Generated by Django 5.1.7 on 2025-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondary_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
