# Generated by Django 5.1.7 on 2025-07-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_secondary_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='account_number',
            field=models.BigIntegerField(),
        ),
    ]
