# Generated by Django 5.1.7 on 2025-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_bankdetail_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currently_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
