# Generated by Django 5.1.7 on 2025-06-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_document_issue_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('citizenship_front', 'Citizenship Front'), ('citizenship_back', 'Citizenship Back'), ('pan_card', 'PAN Card'), ('resume', 'Resume'), ('other', 'Other')], max_length=50),
        ),
    ]
