# Generated by Django 5.1.7 on 2025-06-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_document_issue_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_username', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(blank=True, null=True)),
                ('account_holder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
