# Generated by Django 5.1.7 on 2025-07-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_currently_working_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currently_working',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('currently_working', 'Currently Working'), ('not_working', 'Not Working'), ('deactivated', 'Deactivated')], max_length=20, null=True),
        ),
    ]
