# Generated by Django 5.1.7 on 2025-07-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_currently_working_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('currently_working', 'Currently Working'), ('not_working', 'Not Working'), ('deactivated', 'Deactivated')], default='currently_working', max_length=20),
        ),
    ]
